/:
  method: GET
  alias: 
    - index
  controller: DefaultController # default: DefaultController
  action: index # default: index

/showLogin:
  alias: login
  method: GET
  controller: UserController
  action: showLogin

/login:
  method: POST
  controller: UserController
  action: doLogin
  redirect: /

/logout:
  controller: UserController
  action: doLogout
  redirect: /

/showSignup:
  alias: signup
  method: GET
  controller: UserController
  action: showSignup

/signup:
  method: POST
  controller: UserController
  action: doSignup
  redirect: 
    1: /
    409: /signup

/showPost:
  match: '#^/posts/([0-9]+)$#'
  match_params:
    1: post_id
  action: postShow

/editPost:
  match: '#^/posts/edit/([0-9]*)$#'
  match_params:
    1: post_id
  action: postEdit

/newPost:
  match: '#^/posts/edit/?$#'
  action: postEdit

/savePost:
  method: POST
  alias: posts
  action: postSave
  redirect: /

/killPost:
  match: '#^/posts/([0-9]+)$#'
  method: DELETE
  action: postKill
  redirect: /

/likePost:
  match: '#^/posts/([0-9]+)/like$#'
  match_params:
    1: post_id
  method: PUT
  action: postLikeSave

/unlikePost:
  match: '#^/posts/([0-9]+)/like$#'
  match_params:
    1: post_id
  method: DELETE
  action: postLikeDelete
